### PR TITLE
yaml support chinese and handle voc format

### PR DESCRIPTION
**Pull request by pizixie**
1. support unicode(chinese)
2. handle voc format. ignore "folder" and "filename" node in xml.because they move to other dir sometimes.

### CODE REVIEW

**Comment by alexheat** [comment]
Thank you @pizixie I will check it out.

**Comment by alexheat** [comment]
@pizixie could you possibly provide a sample dataset with the issue that you are addressing with you fix? I want to step through it to make sure that i understand. Thank you

**Comment by pizixie** [comment]
ok, i will upload some file.

**Comment by alexheat** [comment]
Hello @pizixie I have cherry picked your commit for the Chinese characters. I still have some questions about the voc commit. Someone else has submitted a similar commit. Could you help to review it and find the best solution?

**Comment by pizixie** [comment]
[0007.zip](https://github.com/pylabel-project/pylabel/files/12063323/0007.zip)
hi, I am so sorry, Because too busy in week.
There is a sample dataset with VOC format.
you can see that "file"/"folder"/"path" node in xml file.
while "path" is incorrect.

**Comment by pizixie** [comment]
oh...oh...speak chinese.
标注与图片名字相同，后缀不同。这才是简单的关联方式。
很多工具在这些字段中随意记录信息，太混乱了，并且文件还不能移动。

**Comment by pizixie** [comment]
> 

我恐怕没有时间去检查这些commit

**Comment by pizixie** [comment]
> Hello @pizixie I have cherry picked your commit for the Chinese characters. I still have some questions about the voc commit. Someone else has submitted a similar commit. Could you help to review it and find the best solution?


我恐怕没有时间去检查这些commit

**Comment by alexheat** [comment]
Thank you! But I don't speak Chinese :)

**Comment by alexheat** [comment]
Thank you @pizixie I have merged your pull request and released it in v52 https://github.com/pylabel-project/pylabel/releases/tag/v0.1.52

**Comment by pizixie** [comment]
ok,I will test it in future work.

**Pull request merged**
